apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-config 
  namespace: praveen-ns 
data:
  DB_HOST: "mysql-service"
  DB_USER: "root"
  DB_PASSWORD: "rootpassword"
  DB_NAME: "capsule_db"
  DB_PORT: "3306"
  PORT: "3000"
  NODE_ENV: "production"
  SESSION_SECRET: "capsule-k8s-secret-change-in-production"
  SESSION_MAX_AGE: "1800000"
  LOW_STOCK_THRESHOLD: "5"
  HIGH_STOCK_THRESHOLD: "15"
  EMAIL_SERVICE: "gmail"
  EMAIL_USER: "your-email@gmail.com"
  EMAIL_PASS: "your-gmail-app-password"
  SUPPORT_EMAIL: "support@capsule.com"