apiVersion: v1
kind: PersistentVolume
metadata:
  name: retail-pv 
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/general/mysql
    server: 10.0.1.213