apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: retail-pvc 
  namespace: praveen-ns 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: retail-sc
  resources:
    requests:
      storage: 8Gi